/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.UberCars;
import Business.UberCarsDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import static java.awt.image.ImageObserver.WIDTH;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lavina
 */
public class CarsExpiredJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCarsJPanel
     */
    private JPanel userProcessContainer;
    private UberCarsDirectory uberCarsDirectory;
    
    CarsExpiredJPanel(JPanel userProcessContainer, UberCarsDirectory uberCarsDirectory) {
         initComponents();
         this.userProcessContainer = userProcessContainer;
         this.uberCarsDirectory = uberCarsDirectory;
         populateTable();      
    }
    
     public void populateTable() {
         DefaultTableModel dtm = (DefaultTableModel) tblExpiredCars.getModel();
         dtm.setRowCount(0);
         int count = 0;
         Object row [] = new Object[6];
         
         for (UberCars uberCars: uberCarsDirectory.getUberCarsDirectory()){
             if(!uberCars.isValidility()){
             row[0] = uberCars;
             row[1] = uberCars.getModelNumber();
             row[2] = uberCars.getManufacturer();
             row[3] = uberCars.isAvailability();
             row[4] = uberCars.getSeats();
             row[5] = uberCars.getCity();
             dtm.addRow(row);
             count++;
             }
         }
         
         txtExpiredCars.setText(String.valueOf(count));
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblExpiredCars = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtExpiredCars = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblExpiredCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model Name", "Model Number", "Manufacturer", "Available", "Seats", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblExpiredCars);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Total Cars with Expired Maintenance Certificate:");

        txtExpiredCars.setText(" ");
        txtExpiredCars.setEnabled(false);
        txtExpiredCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpiredCarsActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel11)
                .addGap(33, 33, 33)
                .addComponent(txtExpiredCars, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtExpiredCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtExpiredCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpiredCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpiredCarsActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int selectedRow = tblExpiredCars.getSelectedRow();

        if (selectedRow >= 0){
            UberCars uberCars = (UberCars) tblExpiredCars.getValueAt(selectedRow, 0);
            ViewCarsJPanel1 viewCarsJPanel = new ViewCarsJPanel1(userProcessContainer, uberCars, uberCarsDirectory);
            userProcessContainer.add ("ViewCarsJPanel", viewCarsJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null,"Please selecte a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
                Component[] comps = userProcessContainer.getComponents();

        for (Component comp : comps){
            if (comp instanceof ManageCarsJPanel){
            System.out.println(comp);
            ManageCarsJPanel manageP = (ManageCarsJPanel) comp;
            manageP.populateTable();
            }
        }
        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExpiredCars;
    private javax.swing.JTextField txtExpiredCars;
    // End of variables declaration//GEN-END:variables

}
