/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.UberCars;
import Business.UberCarsDirectory;
import java.awt.CardLayout;
import static java.awt.image.ImageObserver.WIDTH;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lavina
 */
public class CurrentCarsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCarsJPanel
     */
    private JPanel userProcessContainer;
    private UberCarsDirectory uberCarsDirectory;
    
    CurrentCarsJPanel(JPanel userProcessContainer, UberCarsDirectory uberCarsDirectory) {
         initComponents();
         this.userProcessContainer = userProcessContainer;
         this.uberCarsDirectory = uberCarsDirectory;
         populateTable();
         
    }
    
     public void populateTable() {
         DefaultTableModel dtm = (DefaultTableModel) tblAvailableCars.getModel();
         dtm.setRowCount(0);
         int count = 0;
         Object row [] = new Object[6];
         DefaultTableModel utm = (DefaultTableModel) tblUnavailableCars.getModel();
         utm.setRowCount(0);
         int count1 = 0;
         Object row1 [] = new Object[6];
         for (UberCars uberCars: uberCarsDirectory.getUberCarsDirectory()){
             if(uberCars.isAvailability()){
             row[0] = uberCars;
             row[1] = uberCars.getModelNumber();
             row[2] = uberCars.getManufacturer();
             row[3] = uberCars.isAvailability();
             row[4] = uberCars.getSeats();
             row[5] = uberCars.getCity();
             dtm.addRow(row);
             count++;
             }
             else {
             row1[0] = uberCars;
             row1[1] = uberCars.getModelNumber();
             row1[2] = uberCars.getManufacturer();
             row1[3] = uberCars.isAvailability();
             row1[4] = uberCars.getSeats();
             row1[5] = uberCars.getCity();
             utm.addRow(row1);
             count1++;
             }
         }
         
         txtAvailableCars.setText(String.valueOf(count));
         txtUnavailableCars.setText(String.valueOf(count1));
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableCars = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUnavailableCars = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAvailableCars = new javax.swing.JTextField();
        txtUnavailableCars = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        tblAvailableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model Name", "Model Number", "Manufacturer", "Available", "Seats", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAvailableCars);

        tblUnavailableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model Name", "Model Number", "Manufacturer", "Available", "Seats", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblUnavailableCars);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Current Available Cars:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Cars unavailable now:");

        txtAvailableCars.setText(" ");
        txtAvailableCars.setEnabled(false);
        txtAvailableCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailableCarsActionPerformed(evt);
            }
        });

        txtUnavailableCars.setEnabled(false);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel11)
                        .addGap(70, 70, 70)
                        .addComponent(txtAvailableCars, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel12)
                        .addGap(77, 77, 77)
                        .addComponent(txtUnavailableCars, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAvailableCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtUnavailableCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAvailableCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailableCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailableCarsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAvailableCars;
    private javax.swing.JTable tblUnavailableCars;
    private javax.swing.JTextField txtAvailableCars;
    private javax.swing.JTextField txtUnavailableCars;
    // End of variables declaration//GEN-END:variables

}
