/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.UberCars;
import Business.UberCarsDirectory;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;

/**
 *
 * @author Lavina
 */
public class UberManageWrkArea extends javax.swing.JPanel {

    /**
     * Creates new form ProductManageWrkArea
     */
    private JPanel userProcessContainer;
    private UberCarsDirectory uberCarsDirectory;

    UberManageWrkArea(JPanel userProcessContainer, UberCarsDirectory uberCarsDirectory) {
         initComponents();
         this.userProcessContainer = userProcessContainer;
         this.uberCarsDirectory = uberCarsDirectory;
         populateTime();
    }
    
    public void populateTime(){
         LocalDateTime dt = LocalDateTime.parse("0000-01-01T00:00:00.000");
         int counttemp = 0;
         for (UberCars uberCars: uberCarsDirectory.getUberCarsDirectory()){
             if(counttemp == 0){
                 dt = uberCars.getUpdatedOn();
                  counttemp++;
             }
             else{
                 if(dt.isBefore(uberCars.getUpdatedOn())){
                     dt = uberCars.getUpdatedOn();
                 }
             }
         }
         DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
         String formattedDt = dt.format(myFormatObj);
         txtUpdateOn.setText(formattedDt);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateProduct = new javax.swing.JButton();
        btnManageProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUpdateOn = new javax.swing.JTextField();

        btnCreateProduct.setText("Create Product");
        btnCreateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProductActionPerformed(evt);
            }
        });

        btnManageProduct.setText("Manage Product");
        btnManageProduct.setPreferredSize(new java.awt.Dimension(127, 2));
        btnManageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductActionPerformed(evt);
            }
        });

        jLabel1.setText("Last Update On:");

        txtUpdateOn.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(txtUpdateOn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnManageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtUpdateOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btnManageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProductActionPerformed
        // TODO add your handling code here:
        CreateCarsJPanel panel = new CreateCarsJPanel(userProcessContainer, uberCarsDirectory);
        userProcessContainer.add("CreateCarsJPanel", panel);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateProductActionPerformed

    private void btnManageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductActionPerformed
        // TODO add your handling code here:
        ManageCarsJPanel panel = new ManageCarsJPanel(userProcessContainer, uberCarsDirectory);
        userProcessContainer.add("ManageCarsJPanel", panel);
        CardLayout cardlayout = (CardLayout) userProcessContainer.getLayout();
        cardlayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateProduct;
    private javax.swing.JButton btnManageProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtUpdateOn;
    // End of variables declaration//GEN-END:variables
}
